apiVersion: v1
kind: ConfigMap
metadata:
  name: sse-consumer-config
data:
  BASE_URL: 'endpoint.example.com'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sse-consumer
  labels:
    app: sse-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sse-consumer
  template:
    metadata:
      labels:
        app: sse-consumer
        base-url: endpoint.example.com 
    spec:
      terminationGracePeriodSeconds: 2
      containers:
      - name: sse-consumer
        image: tutum/curl
        command: ["bash", "-c"]
        args: ["echo BASE_URL: $BASE_URL; /bin/sleep infinity"]
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: sse-consumer-config
